name: Python Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 你的项目用哪个版本写的就填哪个

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint

    - name: Run Black (code formatter)
      run: |
        black . --check  # 只检查，不自动修复

    - name: Run Pylint (static checker)
      run: |
        pylint $(git ls-files '*.py')
